tap "hashicorp/tap"

brew "herdr"
brew "neovim"
brew "starship"
brew "direnv"
brew "mise"
brew "atuin"
brew "granted"
# brew "docker-credential-helper-ecr"
cask "ghostty"
cask "arc"
cask "beyond-compare"
#cask "docker-desktop"
cask "visual-studio-code"
cask "font-meslo-lg-nerd-font"
cask "chatgpt"
cask "claude"
