#!/usr/bin/env bash
set -eo pipefail


list_all() {
  releases_path=https://api.github.com/repos/${ASDF_REPO}
  header=''
  if [ -n "${OAUTH_TOKEN}" ]; then
    header="-H 'Authorization: token ${OAUTH_TOKEN}'"
  fi
  cmd="curl -L -q ${header} -s ${releases_path}"

  # stolen from https://github.com/rbenv/ruby-build/pull/631/files#diff-fdcfb8a18714b33b07529b7d02b54f1dR942
  function sort_versions() {
    sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' | \
      LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | awk '{print $2}'
  }

  # Fetch all tag names, and get only second column. Then remove all unnecesary characters.
  versions=$(eval $cmd | grep -oE "tag_name\": *\".{1,15}\"," | sed 's/tag_name\": *\"v//;s/\",//' | sort_versions)
  echo "$versions"
}

install_bin() {
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"

  case "$os" in
    linux) os="linux" ;;
    darwin) os="darwin" ;;
    *) echo "Unsupported OS: $os" >&2; exit 1 ;;
  esac

  case "$arch" in
    x86_64|amd64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    armv7l) arch="armv7" ;;
    *) echo "Unsupported architecture: $arch" >&2; exit 1 ;;
  esac

  url="https://github.com/${ASDF_REPO}/download/v${ASDF_VERSION}/asdf-v${ASDF_VERSION}-${os}-${arch}.tar.gz"

  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT

  echo "Installing asdf ${ASDF_VERSION} for ${os}/${arch}"
  echo "Downloading: $url"

  curl -fsSL "$url" -o "$tmp/asdf.tar.gz"
  tar -xzf "$tmp/asdf.tar.gz" -C "$tmp"

  # Using 'command' bypasses any local function name collisions
  command install -m 0755 "$tmp/asdf" "${ASDF_INSTALL_DIR}/asdf"

  "${ASDF_INSTALL_DIR}/asdf" --version
}

main() {
  # 1. Initialize repository identifier first
  ASDF_REPO="${ASDF_REPO:-asdf-vm/asdf/releases}"
  # 2. Safe version fallback evaluation order 
  ASDF_VERSION="${ASDF_VERSION:-$(list_all | tail -n1)}"
  ASDF_INSTALL_DIR="${ASDF_INSTALL_DIR:-$HOME/.local/bin}"

  install_bin 
}

main "$@"